#!/bin/bash
saml2aws -a velodnp exec -- aws cloudformation create-stack \
--stack-name SAS-Viya \
--capabilities CAPABILITY_IAM \
--parameters file://parameters.json \
--template-url https://s3-ap-southeast-2.amazonaws.com/sas-viya-installation/quickstart-sas-viya/templates/sas-viya.template.yaml \
--disable-rollback

