# ensure all hosts have /etc/profile.d/http_proxy.sh with our proxy settings
- hosts: all
  become: true
  tasks:
    - name: Ensure proxy settings in profile.d
      copy:
        src: /etc/profile.d/http_proxy.sh
        dest: /etc/profile.d/http_proxy.sh
        owner: root
        group: root
        mode: '0644'

#  Ensure that all hosts have proxy setting configured in /etc/yum.conf. This
#  makes using a local mirror _more difficult_ as the proxy setting interfere
#  with local area connection. The proxy variable is expected to come from
#  outside of this script. One example is to add the options '--extra-vars
#  "proxy=http://example.com"'' to the command-line.
#
# "no_proxy" should be domain suffixes to be excluded from the proxy. IP address ranges are invalid (10.0.0.0/8)
# Eg: .internal,.sas,.viya.sas,visual,prog,stateful,controller,localhost,169.254.169.254
#
    - name: Ensure yum is configured to use a proxy (HttpProxyServer variable required)
      ini_file:
        path: /etc/yum.conf
        section: main
        option: proxy
        value: "{{ HttpProxyServer }}"
        mode: "0644"
        backup: yes
        no_extra_spaces: yes
